apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
  namespace: emart-app
  # annotations:
  #   argocd.argoproj.io/hook: Sync
  #   argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-pod
  template:
    metadata:
      labels:
        app: client-pod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: type
                  operator: In
                  values:
                  - default_node_pool
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: client-pod
              topologyKey: topology.kubernetes.io/hostname
      terminationGracePeriodSeconds: 120
      restartPolicy: Always   
      containers:
      - name: client-container
        image: ghcr.io/omotayoofere/client-api:sha-1bf357b1d66baebcec65037efe81df5ee756c217
        resources:
          requests:
            cpu: "0.2"
            memory: "100Mi"
          limits:
            cpu: "0.2"
            memory: "100Mi"
        ports:
        - containerPort: 4200
          name: client-port
        readinessProbe:
          tcpSocket:
            port: client-port
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: client-port
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 10
        startupProbe:
          tcpSocket:
            port: client-port
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: emart-app
spec:
  selector:
    app: client-pod
  ports:
  - protocol: TCP
    port: 4200
    targetPort: client-port

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: client-pod-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: client-pod

